import { useBlockProps, InnerBlocks } from '@wordpress/block-editor';

/**
 * Save function for Flexible Container block.
 *
 * Note: CSS styles are generated by PHP render_callback using current BBE breakpoints.
 * This allows breakpoint changes to affect all blocks without re-saving.
 */
export default function save({ attributes }) {
	const { blockId } = attributes;

	// Add blockId as a class for CSS targeting (PHP generates the styles)
	const blockProps = useBlockProps.save({
		className: `fc-block ${blockId || ''}`.trim()
	});

	return (
		<div {...blockProps}>
			<InnerBlocks.Content />
		</div>
	);
}
